apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-example
  labels:
    app: go-web-example
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: go-web-example
  template:
    metadata:
      labels:
        app: go-web-example
    spec:
      containers:
      - name: go-web-example
        image: xqian/go-web-hello-world:v0.1
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: go-web 
spec:
  type: NodePort
  selector:
    app: go-web-example 
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31080
  
